version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parserdb
    volumes:
      - ./data:/data
    ports:
      - 5432:5432
